/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BriefingsRouteImport } from './routes/briefings'
import { Route as DirectoryRouteImport } from './routes/directory'
import { Route as MatchesRouteImport } from './routes/matches'
import { Route as PatientsRouteImport } from './routes/patients'
import { Route as PatientsPatientIdRouteImport } from './routes/patients.$patientId'
import { Route as PatientsPatientIdIndexRouteImport } from './routes/patients.$patientId.index'
import { Route as PatientsPatientIdBriefingRouteImport } from './routes/patients.$patientId.briefing'
import { Route as PatientsPatientIdInformationRouteImport } from './routes/patients.$patientId.information'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BriefingsRoute = BriefingsRouteImport.update({
  id: '/briefings',
  path: '/briefings',
  getParentRoute: () => rootRouteImport,
} as any)
const DirectoryRoute = DirectoryRouteImport.update({
  id: '/directory',
  path: '/directory',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchesRoute = MatchesRouteImport.update({
  id: '/matches',
  path: '/matches',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientsRoute = PatientsRouteImport.update({
  id: '/patients',
  path: '/patients',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientsPatientIdRoute = PatientsPatientIdRouteImport.update({
  id: '/$patientId',
  path: '/$patientId',
  getParentRoute: () => PatientsRoute,
} as any)
const PatientsPatientIdIndexRoute = PatientsPatientIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PatientsPatientIdRoute,
} as any)
const PatientsPatientIdBriefingRoute =
  PatientsPatientIdBriefingRouteImport.update({
    id: '/briefing',
    path: '/briefing',
    getParentRoute: () => PatientsPatientIdRoute,
  } as any)
const PatientsPatientIdInformationRoute =
  PatientsPatientIdInformationRouteImport.update({
    id: '/information',
    path: '/information',
    getParentRoute: () => PatientsPatientIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/briefings': typeof BriefingsRoute
  '/directory': typeof DirectoryRoute
  '/matches': typeof MatchesRoute
  '/patients': typeof PatientsRouteWithChildren
  '/patients/$patientId': typeof PatientsPatientIdRouteWithChildren
  '/patients/$patientId/briefing': typeof PatientsPatientIdBriefingRoute
  '/patients/$patientId/information': typeof PatientsPatientIdInformationRoute
  '/patients/$patientId/': typeof PatientsPatientIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/briefings': typeof BriefingsRoute
  '/directory': typeof DirectoryRoute
  '/matches': typeof MatchesRoute
  '/patients': typeof PatientsRouteWithChildren
  '/patients/$patientId/briefing': typeof PatientsPatientIdBriefingRoute
  '/patients/$patientId/information': typeof PatientsPatientIdInformationRoute
  '/patients/$patientId': typeof PatientsPatientIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/briefings': typeof BriefingsRoute
  '/directory': typeof DirectoryRoute
  '/matches': typeof MatchesRoute
  '/patients': typeof PatientsRouteWithChildren
  '/patients/$patientId': typeof PatientsPatientIdRouteWithChildren
  '/patients/$patientId/briefing': typeof PatientsPatientIdBriefingRoute
  '/patients/$patientId/information': typeof PatientsPatientIdInformationRoute
  '/patients/$patientId/': typeof PatientsPatientIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/briefings'
    | '/directory'
    | '/matches'
    | '/patients'
    | '/patients/$patientId'
    | '/patients/$patientId/briefing'
    | '/patients/$patientId/information'
    | '/patients/$patientId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/briefings'
    | '/directory'
    | '/matches'
    | '/patients'
    | '/patients/$patientId/briefing'
    | '/patients/$patientId/information'
    | '/patients/$patientId'
  id:
    | '__root__'
    | '/'
    | '/briefings'
    | '/directory'
    | '/matches'
    | '/patients'
    | '/patients/$patientId'
    | '/patients/$patientId/briefing'
    | '/patients/$patientId/information'
    | '/patients/$patientId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BriefingsRoute: typeof BriefingsRoute
  DirectoryRoute: typeof DirectoryRoute
  MatchesRoute: typeof MatchesRoute
  PatientsRoute: typeof PatientsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/briefings': {
      id: '/briefings'
      path: '/briefings'
      fullPath: '/briefings'
      preLoaderRoute: typeof BriefingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/directory': {
      id: '/directory'
      path: '/directory'
      fullPath: '/directory'
      preLoaderRoute: typeof DirectoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matches': {
      id: '/matches'
      path: '/matches'
      fullPath: '/matches'
      preLoaderRoute: typeof MatchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patients': {
      id: '/patients'
      path: '/patients'
      fullPath: '/patients'
      preLoaderRoute: typeof PatientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patients/$patientId': {
      id: '/patients/$patientId'
      path: '/$patientId'
      fullPath: '/patients/$patientId'
      preLoaderRoute: typeof PatientsPatientIdRouteImport
      parentRoute: typeof PatientsRoute
    }
    '/patients/$patientId/': {
      id: '/patients/$patientId/'
      path: '/'
      fullPath: '/patients/$patientId/'
      preLoaderRoute: typeof PatientsPatientIdIndexRouteImport
      parentRoute: typeof PatientsPatientIdRoute
    }
    '/patients/$patientId/briefing': {
      id: '/patients/$patientId/briefing'
      path: '/briefing'
      fullPath: '/patients/$patientId/briefing'
      preLoaderRoute: typeof PatientsPatientIdBriefingRouteImport
      parentRoute: typeof PatientsPatientIdRoute
    }
    '/patients/$patientId/information': {
      id: '/patients/$patientId/information'
      path: '/information'
      fullPath: '/patients/$patientId/information'
      preLoaderRoute: typeof PatientsPatientIdInformationRouteImport
      parentRoute: typeof PatientsPatientIdRoute
    }
  }
}

interface PatientsPatientIdRouteChildren {
  PatientsPatientIdBriefingRoute: typeof PatientsPatientIdBriefingRoute
  PatientsPatientIdInformationRoute: typeof PatientsPatientIdInformationRoute
  PatientsPatientIdIndexRoute: typeof PatientsPatientIdIndexRoute
}

const PatientsPatientIdRouteChildren: PatientsPatientIdRouteChildren = {
  PatientsPatientIdBriefingRoute: PatientsPatientIdBriefingRoute,
  PatientsPatientIdInformationRoute: PatientsPatientIdInformationRoute,
  PatientsPatientIdIndexRoute: PatientsPatientIdIndexRoute,
}

const PatientsPatientIdRouteWithChildren =
  PatientsPatientIdRoute._addFileChildren(PatientsPatientIdRouteChildren)

interface PatientsRouteChildren {
  PatientsPatientIdRoute: typeof PatientsPatientIdRouteWithChildren
}

const PatientsRouteChildren: PatientsRouteChildren = {
  PatientsPatientIdRoute: PatientsPatientIdRouteWithChildren,
}

const PatientsRouteWithChildren = PatientsRoute._addFileChildren(
  PatientsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BriefingsRoute: BriefingsRoute,
  DirectoryRoute: DirectoryRoute,
  MatchesRoute: MatchesRoute,
  PatientsRoute: PatientsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
